services:
  postgres-test:
    image: postgres:16-alpine
    container_name: desafio-votacao-postgres-test
    environment:
      POSTGRES_DB: votacao_test
      POSTGRES_USER: votacao_test_user
      POSTGRES_PASSWORD: votacao_test_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votacao_test_user -d votacao_test"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_test:
